name: Create Release Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of NuGet Package'
        required: true
        default: ${{date +'%Y-%m-%d'}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${{github.event.inputs.version}}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push Common
      run: dotnet nuget push DarkDhamon.Common.${VERSION}.nupkg --source https://nuget.pkg.github.com/darkdhamon/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push OS Integration
      run: dotnet nuget push DarkDhamon.OS.Integration.${VERSION}.nupkg --source https://nuget.pkg.github.com/darkdhamon/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
